---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deply-yy
  labels: 
    app: spring-pet
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      labels: spring-pet
  strategy:
    type: rollingUpdate
    rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
  template:
    metadata:
      name: deply-yy
      labels: 
        app: spring-pet
  spec:
    containers:
        - name: openmrs
          image: krishna8080/test1:1.0
          ports:
            - containerPort: 8080
              protocol: TCP  
        - name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
      

---
apiVersion: v1
kind: Service
metadata:
  name: spring
  labels: 
    app: spring-yy
spec:
  type: LoadBalancer
  selector: 
    app: spring-yy
  ports:
    - name: server
      port: 8080
      targetPort: 8080 
    - name: nginx 
      port: 80
      targetport: 80                   

