---
apiVersion: v1
kind: Pod
metadata:
  name: nginxjenkins
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 8080
          protocol: TCP
    - image: jenkins/jenkins
      name: jenkins
      ports:
        - containerPort: 8080
          protocol: TCP
